name = "CoralBlox"
uuid = "f00a6e10-004a-11ef-3676-67ec635bc1a2"
authors = ["Pedro Ribeiro de Almeida", "Daniel Tan", "Takuya Iwanaga"]
version = "1.0.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
YAXArrays = "c21b50f5-aa40-41ea-b809-c0f5e47bfa5c"

[compat]
DataStructures = "0.18.20"
YAXArrays = "0.5.8"
julia = "1.10.4"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
CoralBloxPlotExt = "Makie"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
